server:
  port: 8090
spring:
  profiles:
    active: "default"
  config:
    import:
      - "classpath:application_qa.yaml"
      - "classpath:application_prod.yaml"
  application:
    name: loans
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    # database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

# data to read with @Value
build:
  version: 0.0.3-loans

# prefix
loans:
  message: 'Welcome to our localhost DEFAULT loans management application'
  contactDetails:
    name: 'John Steed - CTO'
    email: 'john@bank.com'
  callSupport:
    -(33) 102030405
    -(33) 102030406
