build:
  version: 0.0.3-accounts-REMOTE

accounts:
  message: 'Welcome to our REMOTE DEFAULT accounts management application'
  contactDetails:
    name: 'John Steed - Tech lead'
    email: 'steed@bank.com'
  callSupport:
    -(33) 102030405
    -(33) 102030406