build:
  version: 0.0.3-loans-REMOTE

loans:
  message: 'Welcome to our REMOTE DEFAULT loans management application'
  contactDetails:
    name: 'John Steed - CTO'
    email: 'john@bank.com'
  callSupport:
    -(33) 102030405
    -(33) 102030406
